remove "-z defs" from LDFLAGS since it breaks linking
dist/build/Language/Haskell/HsColour.dyn_o:hscolourzm1zi24zi2zmBwYhdEbf2m3fdRy45AMG_LanguageziHaskellziHsColour_zdfShowLit6_info: error: undefined reference to 'newCAF'
:
dist/build/Language/Haskell/HsColour.dyn_o:sQ3F_info: error: undefined reference to 'stg_upd_frame_info'