ghc_bin_build,ghc_lib_build: defining %ghc_debuginfo allows debuginfo
Needed for ghcX.Y which builds hadrian using %ghc_bin_build
which accidently disabled debuginfo as a side-effect,
which lead to ghcX.Y-compiler .build-id file conflicts:

Error: Transaction test error:
  file /usr/lib/.build-id/4e/f85f81abfd9c031a34af8117ab8e14fcbae536 from install of ghc9.4-compiler-9.4.0.20220623-5.fc36.x86_64 conflicts with file from package ghc9.2-compiler-9.2.3-10.fc36.x86_64

due to missing debuginfo data